---
- name: install certbot
  apt:
    name: certbot
    state: present

- name: obtain/renew certificates
  command: certbot certonly {% if webserver.staging|default(false) %}--staging {% endif %}--webroot --keep-until-expiring --expand --non-interactive --agree-tos -m {{webserver.letsencrypt_email}} -t -w /var/www/html {% for domain in item.domains%}{% for prefix in webserver.prefix %}{% for suffix in webserver.suffix %}-d {{prefix}}{% if prefix!='' %}.{% endif %}{{domain}}{% if suffix!='' %}.{% endif %}{{suffix}} {% endfor %}{% endfor %}{% endfor %}
  register: certUpdate
  changed_when: certUpdate.stdout_lines[2] != 'Certificate not yet due for renewal; no action taken.'
  with_items: "{{ webserver.targets }}"
  notify: reload nginx
  when: webserver.letsencrypt_email|default(false) != false
