- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Copy base nginx config
  template:
    backup: yes
    dest: /etc/nginx/nginx.conf
    src: files/nginx.conf
    
- name: Create reverse proxy entries
  template:
    backup: no
    dest: /etc/nginx/sites-enabled/reverse_proxy.conf
    src: files/reverse_proxy.conf

- include: letsencrypt.yml
