---
- name: Install nginx
  package:
    name: nginx-full
    state: latest

- name: Copy base nginx config
  template:
    backup: yes
    dest: /etc/nginx/nginx.conf
    src: files/nginx.conf
  notify: reload nginx
    
- name: Make sure nginx is enabled and running
  systemd:
    name: nginx.service
    enabled: yes
    daemon_reload: yes
    state: started

- name: www-data needs access to shadow
  user:
    append: yes
    groups: shadow
    name: www-data
